### ISSUE TITLE
create presentation for OFI workshop; Dec 2023

### ISSUE THREAD

**Issue by Rick-Methot-NOAA** [nmfs-stock-synthesis/ICES-course-2023#1]
Prepare a response to the questions listed in the attached workshop description.  Due date is early Dec for the mid-Dec workshop.  Rick will take lead and welcomes support.
[OFI Workshop on State-Space Assessment Models for Stocks with Little or No Age Data_2.pdf](https://github.com/nmfs-stock-synthesis/ss3-trainings/files/13231556/OFI.Workshop.on.State-Space.Assessment.Models.for.Stocks.with.Little.or.No.Age.Data_2.pdf)

**Comment by iantaylor-NOAA** [comment]
Would a Google Doc be a good way to start filling in answers?

**Comment by Rick-Methot-NOAA** [comment]
yes.  then could translate to slides later.

For each Q, I was thinking to describe how SS3 deals with the topic, if it does, then describe shortcomings in the SS3 approach that they might address.

Also, let be sure that FIMS is aware, at least to point of looping in @ChristineStawitz-NOAA

**Comment by e-perl-NOAA** [comment]
Created a [google doc](https://docs.google.com/document/d/1Wk5ZEJS5HWth91_YV9Url7rlnTUfFYUHRmpy-qJmRZY/edit#heading=h.oulo2bjyq43f) for OFI workshop. @Rick-Methot-NOAA and @iantaylor-NOAA, you are the only ones that have edit access aside from me.

**Comment by e-perl-NOAA** [comment]
@Rick-Methot-NOAA have you given this presentation yet? Can I close this issue?

**Comment by Rick-Methot-NOAA** [comment]
presentation was completed.  I will get it into the google ppt folder
